name: 'Check repo in diff action'
description: 'Performs checks on repository found in diff'
author: 'JJ'
inputs:
  diff:
    description: 'Content of the diff'
  minMilestones:
    description: "Minimum number of acceptable milestones"
  minVersion:
    description: "Minimum version of repo to check milestones"
  github-token:
    description: "GitHub token to check the API"
  minPRs:
    description: "Minimum number of closed PRs acceptable"
runs:
  using: 'node12'
  main: 'lib/main.js'
