name: 'repo-in-diff-contains-action'
description: 'Performs checks on repository found in diff'
author: 'JJ'
inputs:
  diff:
    description: 'Content of the diff'
runs:
  using: 'node12'
  main: 'lib/main.js'
