name: "Testing pull requests"
on: [pull_request]

jobs:
  test-prs:
    runs-on: ubuntu-latest
    steps:
      - name: getDiff
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Check this GH action
        uses: JJ/repo-in-diff-gh-action@releases/v1
        with:
          github-token: ${{github.token}}
          minVersion: "1.0.0"
          minPRs: 1

