name: "Info from repo"
on: [pull_request]

jobs:
  obtain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: get-diff
        uses: JJ/github-pr-contains-action@releases/v1
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: dump-steps-test
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: obtain-repo
        uses: JJ/repo-in-diff-gh-action@releases/v0
        with:
          diff: ${{steps.get-diff.outputs.diff}}
